sources:
  - name: raw
    database: dbt-airalo
    schema: raw
    description: "Contains all raw Airalo tables data sources"
    
    tables:
      - name: exchange_rate
        description: "Contains information about currency exchange rates (one row per currency."
        columns:
          - name: currency
            data_type: string
            description: "Currency code (USD, EUR, GBP, JPY, AUD, CAD, SGD, ARS)."
            tests:
              - not_null
              - unique
          - name: usd_rate
            data_type: float64
            description: "Exchange rate of the currency to USD."
            tests:
              - not_null
        
      - name: order
        description: "Contains information about orders (one row per order x status change)."
        columns:
          - name: order_id
            data_type: string
            description: "Orders identifier."
            tests:
              - not_null
              - unique
          - name: user_id
            data_type: string
            description: "Foreign key to users table"
            tests:
              - not_null
          - name: created_at
            data_type: timestamp
            description: "Timestamp when the order was created"
            tests:
              - not_null
          - name: updated_at
            data_type: timestamp
            description: "Timestamp when the order was last updated"
          - name: amount
            data_type: float64
            description: "Amount of the order"
          - name: currency
            data_type: string
            description: "Currency of the amount (e.g., USD, GBP)"
          - name: esim_package
            data_type: string
            description: "Name of the eSIM package purchased (10GB - 30 Days, Unlimited, 1GB - 7 Days, or 3GB - 30 Days)."
          - name: payment_method
            data_type: string
            description: "Payment method used for the order (Airmoney, Apple Pay, Credit Card, Google Pay, PayPal)."
          - name: card_country
            data_type: string
            description: "Country of the card used for payment"
          - name: destination_country
            data_type: string
            description: "Country where the eSIM will be used"
          - name: status
            data_type: string
            description: "Status of the order (completed, refunded, failed)"

      - name: user
        description: "Contains information about users (one row per user)."
        columns:
          - name: user_id
            data_type: integer
            description: "Unique identifier for each user (primary key)"
            tests:
              - not_null
              - unique
          - name: created_at
            data_type: timestamp
            description: "Timestamp when the user was created"
          - name: platform
            data_type: string
            description: "Platform used by the user (iOS, Android, Web)"
          
          - name: acquisition_channel
            data_type: string
            description: "Acquisition channel of the user (Affiliate, Facebook, Google Ads, Organic, Referral)"
          - name: ip_country
            data_type: string
            description: "Country derived from the user's IP address (ISO country code)."
            tests:
              - not_null